### ISSUE TITLE
[vRP] identification Error 

### ISSUE THREAD

**Issue by mohamedstryker** [vRP-Official-Developers/dunko_vrp#268]
hey guys !! 
i've identfication error in my vrp server
xampp and heidi sql works perfect !!
and i've also got this error 
![image](https://user-images.githubusercontent.com/98905806/152204621-c1a82cdb-9a32-4792-8c4e-2d890d7f5015.png)
![image](https://user-images.githubusercontent.com/98905806/152204714-9221722d-c444-44ff-85be-74f1dbfff509.png)

**Comment by callum1337** [comment]
If you read the bottom it shows your credentials are wrong and you have been denied access to the database, this is nothing Dunko's vRP can help with therefore I will be closing this issue :)
